hrmanagment/hrmanagment/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import include


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^', include('offerletter.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hrmanagment/offerletter/urls.py
from django.conf.urls import url

app_name = 'offerletter'

from offerletter import views

urlpatterns = [
    url(r'^$', views.home_age, name='home_age'),
    url(r'^dashboard', views.dashboard_page, name='dashboard_page'),
    url(r'^profile', views.profile_page, name='profile'),
    # url(r'^profile$', views.profile_page, name='profile_page'),
    url(r'^add', views.adding_cand, name='add_cand'),
    url(r'^details', views.details_page, name='cand_list'),
    url(r'^offer', views.offer_letter, name='offerltr'),
    url(r'^genoffer', views.gen_offer, name='gen_offer'),
    url(r'^takecand/(?P<id>[0-9]+)/', views.take_candidate, name='takecandidate'),
    url(r'^image', views.save_image, name='save_image')

]

hrmanagment/offerletter/models.py
    # -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Profile(models.Model):
    first_name = models.CharField(max_length=50)
    mobile_number = models.BigIntegerField()
    email = models.EmailField()
    father_name = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    district = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    pin_code = models.BigIntegerField()


class Image(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='offerletter/')

hrmanagment/offerletter/forms.py
from django import forms

from .models import Profile, Image


class AddForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'mobile_number', 'email', 'father_name', 'city', 'district', 'state', 'pin_code')


from registration.forms import RegistrationForm


class RegForm(RegistrationForm):
    def __init__(self, *args, **kwargs):
        super(RegForm, self).__init__(*args, **kwargs)

        for fieldname in ['usename', 'email', 'password1', 'password2', ]:
            self.fields[fieldname].help_text = None
            self.fields[fieldname].lables = False


class ImgForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('name', 'image')

# class UserCreateForm(UserCreationForm):
#     email = forms.EmailField(required=True)
#
#     def __init__(self, *args, **kwargs):
#         super(UserCreateForm, self).__init__(*args, **kwargs)
#             self.fields['email'].help_text = ''

hrmanagment/offerletter/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import base64

from django.http import HttpResponse
from django.shortcuts import render, redirect
# Create your views here.
from django.template.loader import get_template
from xhtml2pdf import pisa

from offerletter.forms import AddForm, ImgForm
from offerletter.models import Profile, Image
from offerletter.utils import render_to_pdf
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.template import RequestContext
from django.conf import settings
# import ho.pisa as pisa
import cStringIO as StringIO
import cgi
import os


def home_age(requets):
    print('home_age called')
    return render(requets, 'offerletter/home.html')


#
#
# def profile_page(request):
#     print('profile_page called')
#     return render(request, 'offerletter/profile-page.html')
#
#
# def adding_page(request):
#     print('adding_page called')
#     if request.method == 'POST':
#         form = AddForm(request.POST)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.save()
#             return redirect('details_page')
#     else:
#         form = AddForm
#     return render(request, 'offerletter/add-page.html', {'form': form})
#
#
def details_page(request):
    print('details_page called')
    details = Profile.objects.all()
    return render(request, 'offerletter/profile-details.html', {'posts': details})


def dashboard_page(request):
    print('dashboard_page called')
    return render(request, 'offerletter/dashboard.html')


def profile_page(request):
    print('profile_page called')
    return render(request, 'offerletter/profile-page.html')


def adding_cand(request):
    print('adding_page called')
    if request.method == 'POST':
        form = AddForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            details = Profile.objects.all()
            return render(request, 'offerletter/profile-details.html', {'posts': details})
    else:
        print('adding_cand called')
        form = AddForm
    return render(request, 'offerletter/add-page.html', {'form': form})


def offer_letter(request):
    print('offer letter called')
    return render(request, 'offerletter/offer.html')


def gen_offer(request):
    print('gen_offer called')
    details = Profile.objects.all()
    return render(request, 'offerletter/get_list_offer.html', {'posts': details})


def take_candidate(request, id):
    print('takecandidate called', request.POST)
    data = Profile.objects.get(id=id)
    try:
        image = Image.objects.all()
        encoded_string = base64.b64encode(image)
        print('details', encoded_string)
    except Exception as e:
        print('exception as e', e)
    template = get_template('offerletter/offer_letter_temp.html')
    print('after the template')
    context = {
        "first_name": data.first_name,
        "mobile_number": data.mobile_number,
        "email": data.email,
        "father_name": data.father_name,
        "city": data.city,
        "district": data.district,
        "state": data.state,
        "pincode": data.pin_code,
        "image": image[0].image
    }
    html = template.render(context)
    pdf = render_to_pdf('offerletter/offer_letter_temp.html', context)
    # return render(request, 'offerletter/offer_letter_temp.html')
    if pdf:
        response = HttpResponse(pdf, content_type='application/pdf')
        filename = 'offer_letter_%s.pdf' % (data.first_name)
        content = "inline; filename='%s'" % (filename)
        response['Content-Disposition'] = content
        return response
    return HttpResponse('Not Found')
    print('after the pdf')
    return pdf
    # return HttpResponse(pdf, content_type='application/pdf')
    # return render(request, 'offerletter/offer_letter_temp.html',{'data': data})


def save_image(request):
    print('add image called')
    if request.method == 'POST':
        print('after the if request post method')
        form = ImgForm(request.POST, request.FILES)
        print('after the img form FILES')
        if form.is_valid():
            print('after the form is valid')
            post = form.save(commit=False)
            print('afetre comit false')
            post.save()
            print('after the save')
            details = Image.objects.all()
            # print('images', details_page())
            return render(request, 'offerletter/offer.html', {'data': details})
    else:
        form = ImgForm
    return render(request, 'offerletter/addimage.html', {'form': form})

hrmanagment/offerletter/templates/offerletter/add-page.html
{% extends 'offerletter/home.html' %}
{% load bootstrap4 %}
{% block content %}

<!--<h3>profile page</h3>-->
<div class="container jumbotron col-md-4">

<form method="POST" class="post-form">
    {% csrf_token %}
    <div class="form-group">
        {% bootstrap_form form %}
        <button type="submit" class="save btn btn-default">Save</button>
   </div>

    </form>

    </div>
</div>
{% endblock %}

hrmanagment/offerletter/templates/offerletter/addimage.html
{% extends 'offerletter/home.html' %}
{% load bootstrap4 %}

{% block content %}
 {% if request.user.is_authenticated %}
<div class="container jumbotron col-md-4">
<p>add image</p>
<form method="POST" class="post-form" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        {% bootstrap_form form %}
        <button type="submit" class="save btn btn-default">Save</button>
   </div>

    </form>
</div>
{% else %}
{{ 'Plz login to continue' }}
{% endif %}

    {% endblock %}

hrmanagment/offerletter/templates/offerletter/dashboard.html
{% extends 'offerletter/home.html' %}
{% block content %}
 {% if request.user.is_authenticated %}
<div class="container col-md-10 takeleft">
    <div class="col-md-12">
    <a class="btn btn-primary btn-lg" href="{% url 'offerletter:cand_list' %}">Candidates</a>
        <a class="btn btn-primary btn-lg pull-right" href="{% url 'offerletter:add_cand' %}">Add Candidates</a>
    </div>
</div>
{% else %}
{{ 'Plz login to continue' }}
{% endif %}

    {% endblock %}

hrmanagment/offerletter/templates/offerletter/get_list_offer.html
{% extends 'offerletter/home.html' %}
{% block content %}
 {% if request.user.is_authenticated %}
<div class="container col-md-10">
    <form action="">
    <table class="table">
  <thead>
    <tr>
        <th>id</th>
        <th>NAME</th>
        <th>MOBILE NUMBER</th>
        <th>Email</th>
    </tr>
</thead>
<tbody>
{% for task in posts %}
    <tr class="hideblue">
        <td>{{task.id}}</td>
        <td><a  href="{% url 'offerletter:takecandidate' task.id %}">{{task.first_name}}</a></td>
        <td>{{task.mobile_number}}</td>
        <td>{{task.email}}</td>
    </tr>
{% endfor %}
</tbody>
</table>
    </form>
</div>
{% else %}
{{ 'Plz login to continue' }}
{% endif %}

    {% endblock %}
<style>
    table, th, td {
    border: 1px solid black;
    <!--color : black;-->
}
.hideblue a {
background-color: #d11250;
    color: white;
    font-weight:bold;
}
</style>

hrmanagment/offerletter/templates/offerletter/home.html
{% load staticfiles %}

<html>
<head>
        <title>Home</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/home.css' %}">
</head>
<body>
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 getleft">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Nescode</a>
      <input class="form-control form-control-dark w-50" type="text" placeholder="Search" aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item dropdown">
            {% if request.user.is_authenticated %}
          <li class="nav-items"><a href="{% url 'auth_logout' %}">Log Out</a></li>
          {% else %}
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Action
          </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'registration_register' %}">Sign Up</a>
          <a class="dropdown-item" href="{% url 'auth_login' %}">Sign In</a>
        </div>
      </li>
          {% endif %}
      </ul>
    </nav>
{% if request.user.is_authenticated %}
<div class="container-fluid getleft">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'offerletter:profile' %}">
                  <span data-feather="home"></span>
                  Profile <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'offerletter:offerltr' %}">
                  <span data-feather="file"></span>
                  Offer Letter
                </a>
              </li>

            </ul>
          </div>
        </nav>
      </div>
</div>
{% endif %}
<div class="container">
    {% block content %}
    {% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

hrmanagment/offerletter/templates/offerletter/offer.html
{% extends 'offerletter/home.html' %}
{% block content %}
 {% if request.user.is_authenticated %}
<div class="container col-md-10">
    <h3>Generate Offer Letter</h3>
    <a class="btn btn-primary btn-lg" href="{% url 'offerletter:gen_offer' %}">generate</a>
    <a class="btn btn-primary btn-lg" href="{% url 'offerletter:save_image' %}">Add image</a>
</div>

{% else %}
{{ 'Plz login to continue' }}
{% endif %}

    {% endblock %}

hrmanagment/offerletter/templates/offerletter/profile-details.html
<!DOCTYPE html>
{% extends 'offerletter/home.html' %}

{% block content %}
<!--<h3>profile page</h3>-->
<!--<h3>profile page</h3>-->
<div class="container col-md-10">
        <table class="table">
  <thead>
    <tr>
        <th>NAME</th>
        <th>MOBILE NUMBER</th>
        <th>Email</th>
    </tr>
</thead>
<tbody>
{% for task in posts %}
    <tr>
        <td>{{task.first_name}}</td>
        <td>{{task.mobile_number}}</td>
        <td>{{task.email}}</td>
    </tr>
{% endfor %}
</tbody>
</table>
    </div>

{% endblock %}
<style>
    table, th, td {
    border: 1px solid black;
}
.taketop {
margin-top: -45px;
margin-left: -40px;
}
</style>

hrmanagment/offerletter/templates/offerletter/profile-page.html
<!DOCTYPE html>
{% extends 'offerletter/home.html' %}

{% block content %}
<!--<h3>profile page</h3>-->
<div class="container col-md-10">
    <div class="col-md-12">
        <a class="btn btn-primary btn-lg" href="{% url 'offerletter:cand_list' %}">Candidates</a>
        <a class="btn btn-primary btn-lg pull-right" href="{% url 'offerletter:add_cand' %}">Add Candidates</a>
    </div>
</div>
{% endblock %}

hrmanagment/templates/base.html
{% load staticfiles %}

<html>
<head>
    <title>Home</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
</head>
<body>
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 getleft">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Nescode</a>
    <input class="form-control form-control-dark w-50" type="text" placeholder="Search" aria-label="Search">
    <ul class="navbar-nav px-5">
        <li class="nav-item dropdown">
            {% if request.user.is_authenticated %}
        <li class="nav-items"><a href="{% url 'auth_logout' %}">Log Out</a></li>
        {% else %}
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false" aria-labelledby="btnGroupDrop1">
            Action
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'registration_register' %}">Sign Up</a>
            <a class="dropdown-item" href="{% url 'auth_login' %}">Sign In</a>
        </div>
        </li>
        {% endif %}
    </ul>
</nav>
{% if request.user.is_authenticated %}
<div class="container-fluid getleft">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
            <div class="sidebar-sticky">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'offerletter:profile' %}">
                            <span data-feather="home"></span>
                            Profile <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'offerletter:offerltr' %}">
                            <span data-feather="file"></span>
                            Offer Letter
                        </a>
                    </li>

                </ul>
            </div>
        </nav>
    </div>
</div>
{% endif %}
<div class="container">
    {% block content %}
    {% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>
</html>

<!--<nav class="navbar navbar-expand-lg navbar-light bg-light">-->
<!--<a class="navbar-brand" href="#">NESCODE</a>-->
<!--<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">-->
<!--<span class="navbar-toggler-icon"></span>-->
<!--</button>-->
<!--<div class="collapse navbar-collapse" id="navbarNavDropdown">-->
<!--<ul class="navbar-nav ml-auto">-->
<!--{% if request.user.is_authenticated %}-->
<!--<li class="nav-items"><a href="{% url 'auth_logout' %}">Log Out</a></li>-->
<!--{% else %}-->
<!--<li class="nav-item dropdown">-->
<!--<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--Action-->
<!--</a>-->
<!--<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">-->
<!--<a class="dropdown-item" href="{% url 'registration_register' %}">Sign Up</a>-->
<!--<a class="dropdown-item" href="{% url 'auth_login' %}">Sign In</a>-->
<!--</div>-->
<!--</li>-->
<!--{% endif %}-->
<!--</ul>-->
<!--</div>-->
<!--</nav>-->
<!--{% if request.user.is_authenticated %}-->
<!--<div class="container">-->
<!--<div class="row">-->
<!--<div class="col-md-4">-->
<!--<nav>-->
<!--<ul class="nav">-->
<!--<li class="nav-item left-bar"> <a href="{% url 'offerletter:profile' %}">Profile</a></li>-->

<!--<li class="nav-item left-bar"><a href="{% url 'offerletter:offerltr' %}">Offer Letter</a></li>-->
<!--&lt;!&ndash;<li class="nav-item left-bar">1</li>&ndash;&gt;-->
<!--</ul>-->
<!--</nav>-->

<!--</div>-->
<!--</div>-->
<!--</div>-->
<!--{% endif %}-->


<!--<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>-->
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>-->
<!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>-->
<!--</body>-->
<!--</html>-->